# ----- CLEO -----
# File: config_colls0d.yaml
# Project: config
# Created Date: Thursday 5th December 2024
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Thursday 5th December 2024
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for 0D box model of collisions using CLEO.
# Note: The inital superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "scripts/collisions0d/initconds.py" for usage) and likewise
# for "grid_filename".

### Initial Conditions Parameters for Python Script ###
python_initconds:
  paths:
    savefigpath: XXX
    sharepath: XXX
  grid:
    zgrid: [0, 100, 100]                                      # [max, min, spacing] of gridbox boundaries in z direction
    xgrid: [0, 100, 100]                                      # [max, min, spacing] of gridbox boundaries in x direction
    ygrid: [0, 100, 100]                                      # [max, min, spacing] of gridbox boundaries in y direction
  supers:
    dryradius: 1.0e-16                                          # all SDs have negligible solute [m]
    rspan: [1.0e-7, 9.0e-5]  # max and min range of radii to sample [m]
    volexpr0: 30.531e-6  # peak of volume exponential distribution [m]
    numconc: 8388608  # = 2^23 = total no. conc of real droplets [m^-3]

### SDM Runtime Parameters ###
domain:
  nspacedims: 0                                                 # no. of spatial dimensions to model
  ngbxs: 1                                                      # total number of Gbxs
  maxnsupers: X                                                 # maximum number of SDs

timesteps:
  CONDTSTEP: 1                                                  # time between SD condensation [s]
  COLLTSTEP: 1                                                  # time between SD collision [s]
  MOTIONTSTEP: 5                                                # time between SDM motion [s]
  COUPLTSTEP: 3600                                              # time between dynamic couplings [s]
  OBSTSTEP: 300                                                 # time between SDM observations [s]
  T_END: 3600                                                   # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename: XXX                                       # name of file for values of physical constants
  grid_filename: XXX                                            # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                              # type of initialisation of super-droplets
  initsupers_filename: XXX                                      # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename: XXX                                           # .txt filename to copy configuration to
  stats_filename: XXX                                           # .txt file to output runtime statistics to
  zarrbasedir: XXX                                              # zarr store base directory
  maxchunk: 2500000                                             # maximum no. of elements in chunks of zarr store array
